Description: Aquia IAM cross-account Security Auditor Role

Parameters:
  accountID:
    Type: String
    Description: Aquia AWS Z2F Account ID
  
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ReadOnlyAuditRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'ReadOnlyAuditRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              AWS: !Sub 'arn:aws:iam::${accountID}:root'
            Action: 
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/SecurityAudit'
      Tags:
        - Key: 'tag-key'
          Value: 'tag-value'

Outputs:
  RoleARN:
    Description: 'ARN of the read-only audit role'
    Value: !GetAtt ReadOnlyAuditRole.Arn